"""empty message

Revision ID: 8b9d817b5114
Revises: 364f35727edc
Create Date: 2022-03-16 14:28:58.979233

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8b9d817b5114'
down_revision = '364f35727edc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manager',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('feedback_author_id_fkey', 'feedback', type_='foreignkey')
    op.create_foreign_key(None, 'feedback', 'manager', ['author_id'], ['id'])
    op.drop_constraint('monitor_id_fkey', 'monitor', type_='foreignkey')
    op.create_foreign_key(None, 'monitor', 'manager', ['id'], ['id'])
    op.drop_constraint('professor_id_fkey', 'professor', type_='foreignkey')
    op.create_foreign_key(None, 'professor', 'manager', ['id'], ['id'])
    op.drop_constraint('question_author_id_fkey', 'question', type_='foreignkey')
    op.create_foreign_key(None, 'question', 'manager', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.create_foreign_key('question_author_id_fkey', 'question', 'user', ['author_id'], ['id'])
    op.drop_constraint(None, 'professor', type_='foreignkey')
    op.create_foreign_key('professor_id_fkey', 'professor', 'user', ['id'], ['id'])
    op.drop_constraint(None, 'monitor', type_='foreignkey')
    op.create_foreign_key('monitor_id_fkey', 'monitor', 'user', ['id'], ['id'])
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.create_foreign_key('feedback_author_id_fkey', 'feedback', 'user', ['author_id'], ['id'])
    op.drop_table('manager')
    # ### end Alembic commands ###
